#!/usr/bin/env python3
"""SFX와 내레이션 wav를 base64로 임베드한 _audio_data.js 빌드."""
import base64
import mimetypes
from pathlib import Path

ROOT = Path(__file__).parent
SFX_DIR = ROOT / "sfx"
NAR_DIR = ROOT / "narration"
OUT = ROOT / "_audio_data.js"

def to_data_uri(path: Path) -> str:
    mime, _ = mimetypes.guess_type(str(path))
    if not mime:
        mime = "audio/mpeg" if path.suffix == ".mp3" else "audio/wav"
    b64 = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{b64}"

def main():
    total_in = 0
    # SFX (mp3)
    sfx_files = sorted(SFX_DIR.glob("*.mp3"))
    sfx_map = {}
    for f in sfx_files:
        key = f.stem  # fanfare, level-up, ...
        sfx_map[key] = to_data_uri(f)
        sz = f.stat().st_size
        total_in += sz
        print(f"SFX  {key}: {sz/1024:.1f} KB")

    # TTS narration: 우선 mp3, 없으면 wav
    tts_map = {}
    for i in range(1, 18):
        mp3_path = NAR_DIR / f"slide-{i:02d}_gemini_tts.mp3"
        wav_path = NAR_DIR / f"slide-{i:02d}_gemini_tts.wav"
        if mp3_path.exists():
            tts_map[str(i)] = to_data_uri(mp3_path)
            sz = mp3_path.stat().st_size
            total_in += sz
            print(f"TTS  slide-{i:02d}: {sz/1024:.1f} KB (mp3)")
        elif wav_path.exists():
            tts_map[str(i)] = to_data_uri(wav_path)
            sz = wav_path.stat().st_size
            total_in += sz
            print(f"TTS  slide-{i:02d}: {sz/1024:.1f} KB (wav)")
        else:
            print(f"MISS slide-{i:02d}")
    print(f"\nTotal raw audio: {total_in/1024/1024:.2f} MB")

    # Write JS
    lines = ["// Generated by _build_audio.py - DO NOT EDIT MANUALLY", ""]
    lines.append("window.__SFX__ = {")
    for k, v in sfx_map.items():
        lines.append(f"  {k!r}: {v!r},")
    lines.append("};")
    lines.append("")
    lines.append("window.__TTS__ = {")
    for k, v in tts_map.items():
        lines.append(f"  {k!r}: {v!r},")
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    total_kb = OUT.stat().st_size / 1024
    print(f"\nWrote {OUT.name} ({total_kb:.1f} KB)")

if __name__ == "__main__":
    main()
